/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xomios_internal_Socket */

#ifndef _Included_org_xomios_internal_Socket
#define _Included_org_xomios_internal_Socket
#ifdef __cplusplus
extern "C" {
#endif
#undef org_xomios_internal_Socket_AF_INET
#define org_xomios_internal_Socket_AF_INET 10L
#undef org_xomios_internal_Socket_AF_INET6
#define org_xomios_internal_Socket_AF_INET6 11L
#undef org_xomios_internal_Socket_AF_UNIX
#define org_xomios_internal_Socket_AF_UNIX 12L
#undef org_xomios_internal_Socket_AF_UNSPEC
#define org_xomios_internal_Socket_AF_UNSPEC 99L
#undef org_xomios_internal_Socket_SOCK_STREAM
#define org_xomios_internal_Socket_SOCK_STREAM 10L
#undef org_xomios_internal_Socket_SOCK_DGRAM
#define org_xomios_internal_Socket_SOCK_DGRAM 11L
#undef org_xomios_internal_Socket_SOCK_RAW
#define org_xomios_internal_Socket_SOCK_RAW 12L
/*
 * Class:     org_xomios_internal_Socket
 * Method:    createSocket
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xomios_internal_Socket_createSocket
  (JNIEnv *, jobject);

/*
 * Class:     org_xomios_internal_Socket
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xomios_internal_Socket_close
  (JNIEnv *, jobject);

/*
 * Class:     org_xomios_internal_Socket
 * Method:    connect
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_org_xomios_internal_Socket_connect
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     org_xomios_internal_Socket
 * Method:    recv
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xomios_internal_Socket_recv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xomios_internal_Socket
 * Method:    send
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_xomios_internal_Socket_send
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
